parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: {{ db_name }}
    database_user: {{ db_user }}
    database_password: {{ db_pass }}
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: {{ secret }}
    requiredlocales: en|fr|es|de
    defaultlocale: en
    multilanguage: true
    sentry.dsn: 'https://XXXXXXXX:XXXXXXXX@app.getsentry.com/XXXX'
    cdnpath: ''
    websitetitle: Coolandbed
    searchport: 9200
    searchindexname: myproject
    searchindexprefix: myproject
    analytics.googletagmanager: GTM-XXXXXX

